name: Update Version

on:
  schedule:
    - cron: '0 */12 * * *'
    
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    container:
      image: fedora:41

    steps:
      - name: Install dependencies
        run: |
          dnf install -y git rpm-build createrepo_c curl jq tar

      - name: Prepare and Build RPM
        run: |
          git clone https://${{ secrets.PAT }}@github.com/itsnotsos/materialgram-repo.git repo
          cd repo
          git pull origin main
          chmod +x update.sh
          ./update.sh
          chmod +x build.sh
          ./build.sh
